---
# Configuration file for CML jobs
# Contains all job definitions and their parameters

jobs:
  create_env:
    name: Create Python Environment
    script: template/create_environment.py
    kernel: python3
    runtime_id: "docker.repository.cloudera.com/cloudera/cdsw/ml-runtime-pbj-jupyterlab-python3.11-standard:2025.01.3-b8"
    cpu: 1
    memory: 2
    timeout: 1800  # 30 minutes
    environment: {}
    arguments: ""

  scheduled_report:
    name: random job
    script: template/scripts/run_hello_world.py
    kernel: python3
    runtime_id: docker.repository.cloudera.com/cloudera/cdsw/ml-runtime-pbj-jupyterlab-python3.11-standard:2025.01.3-b8
    cpu: 1
    memory: 2
    timeout: 600  # 10 minutes
    schedule: "0 9 * * 1"  # Every Monday at 9 AM
