---
# Configuration file for CML jobs
# Contains all job definitions and their parameters

jobs:
  create_env:
    name: Create Python Environment
    script: create_environment.py
    kernel: python3
    runtime_id: 91
    cpu: 1
    memory: 2
    timeout: 1800  # 30 minutes
    environment: {}
    arguments: ""

  data_processing:
    name: Process Data
    script: scripts/hello_world.py
    kernel: python3
    runtime_id: 91
    cpu: 2
    memory: 4
    timeout: 3600  # 1 hour
    environment:
      DATA_PATH: /data/raw
      OUTPUT_PATH: /data/processed
    arguments: --name "CML User" --repeat 3
    parent_job_id: create_env  # This makes the job dependent on create_env

  model_training:
    name: Train Machine Learning Model
    script: scripts/model_training.py
    kernel: python3
    runtime_id: 91
    cpu: 4
    memory: 8
    timeout: 7200  # 2 hours
    environment:
      MODEL_DIR: /models
    arguments: --n_samples 5000 --n_features 30 --model_name demo_model
    parent_job_id: data_processing  # Runs after data processing

  scheduled_report:
    name: Weekly Status Report
    script: scripts/example_job.py
    kernel: python3
    runtime_id: 91
    cpu: 1
    memory: 2
    timeout: 600  # 10 minutes
    schedule: "0 9 * * 1"  # Every Monday at 9 AM
