---
# Configuration file for CML jobs
# Contains all job definitions and their parameters

jobs:
  create_env:
    name: Create Python Environment
    script: template/create_environment.py
    kernel: python3
    runtime_id: 91
    cpu: 1
    memory: 2
    timeout: 1800  # 30 minutes
    environment: {}
    arguments: ""

  data_processing:
    name: Process Data
    script: template/scripts/hello_world.py
    kernel: python3
    runtime_id: 91
    cpu: 2
    memory: 4
    timeout: 3600  # 1 hour
    environment:
      DATA_PATH: /data/raw
      OUTPUT_PATH: /data/processed
    arguments: --debug
    parent_job_id: create_env  # This makes the job dependent on create_env
